const team_src = [
  {
    img: "/Anuj.png",
    name: "Anuj Prakash Gupta",
    subtext: "General Secretary",
    instagram: "https://www.instagram.com/anujgupta_7/",
    linkedin: "https://www.linkedin.com/in/anuj-gupta-40571b1b9/",
    github: "https://github.com/anujgupta-7",
    description:
      "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Utkarsh.png",
    name: "Utkarsh Prakash",
    subtext: "Core Team Lead",
    linkedin: "#",
    github: "#",
    instagram: "#",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Ayush.png",
    name: "Ayush Kushwaha",
    subtext: "Financial Head",
    instagram: "https://www.instagram.com/_ayushx._/",
    linkedin: "https://www.linkedin.com/in/ayushkx/",
    github: "https://github.com/ayushkx",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Alisha.png",
    name: "Alisha Srivastava",
    subtext: "Editorial & Creative Head",
    linkedin: "#",
    github: "#",
    instagram: "#",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Shivansh.png",
    name: "Shivansh Choudhary",
    subtext: "Technical Head",
    linkedin: "#",
    github: "#",
    instagram: "#",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Tushar.png",
    name: "Tushar Sharma",
    subtext: "Management Head",
    instagram: "https://www.instagram.com/iamtushar_24/",
    linkedin: "https://www.linkedin.com/in/tushar-sharma-49853b202",
    github: "https://github.com/iamtushar24",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
  {
    img: "/Pankaj.png",
    name: "Pankaj Rathore",
    subtext: "Web Team Head",
    linkedin: "#",
    github: "#",
    instagram: "#",
    description: "We have a group of young exciting minds who works continuously for the development of the society and their team.",
  },
];

const events_src = [
  {
    img: "/assets/events/epixel.png",
    name: "EPIXEL",
    subtext: "Design Workshop",
    instagram: "https://www.instagram.com/p/CiheI5RP9AM/",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
  {
    img: "/assets/events/tomorrow's tesla.png",
    name: "Tomorrow's Tesla",
    subtext: "Pitch Your Billion-dollar Idea",
    instagram: "https://www.instagram.com/p/Ccx7Ydsp6a0/",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
  {
    img: "/assets/events/mighty maneuver.png",
    name: "Mighty Maneuver",
    subtext: "LFR Racing Event",
    instagram: "https://www.instagram.com/p/Ccx7RcWJqTV/",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
  {
    img: "/assets/events/orientation.png",
    name: "Orientation Program",
    subtext: "Introduction to Quanta for Freshers",
    instagram: "https://www.instagram.com/p/CWiMbswvatO/",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
  {
    img: "/assets/events/tech bias.png",
    name: "Tech Bias",
    subtext: "Our Flagship Workshop",
    instagram: "https://www.instagram.com/p/CXGMsXKPUbI/",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
  {
    img: "/assets/events/electrohunt.png",
    name: "Electrohunt",
    subtext: "A Thrilling Quiz",
    instagram: "#",
    description: "Quanta conducts various events throughout the year, here is glimpse of some events conducted by QUANTA",
  },
];

export { team_src, events_src };
